/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk_7.pkg1;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdul Malik Muzakir
 */
public class index extends javax.swing.JFrame {
    String tampil = ""; 
    double bayar = 0;
    String diskon = "";
    private String level;
        
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }
    
    public void level(String l){
        level = l;
        if(level.equals("admin")){
            index index = new index();
            index.setVisible(false);
            this.dispose();
            login login = new login();
            login.setVisible(true);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        namaPemesan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        seblak = new javax.swing.JCheckBox();
        basoBakar = new javax.swing.JCheckBox();
        kebabTurki = new javax.swing.JCheckBox();
        frenchFries = new javax.swing.JCheckBox();
        burger = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jumlah1 = new javax.swing.JTextField();
        jumlah2 = new javax.swing.JTextField();
        jumlah3 = new javax.swing.JTextField();
        jumlah4 = new javax.swing.JTextField();
        jumlah5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cappucino = new javax.swing.JCheckBox();
        kopiTubruk = new javax.swing.JCheckBox();
        boba = new javax.swing.JCheckBox();
        jusMangga = new javax.swing.JCheckBox();
        jusAlpukat = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jumlah6 = new javax.swing.JTextField();
        jumlah7 = new javax.swing.JTextField();
        jumlah8 = new javax.swing.JTextField();
        jumlah9 = new javax.swing.JTextField();
        jumlah10 = new javax.swing.JTextField();
        yougert = new javax.swing.JCheckBox();
        mochi = new javax.swing.JCheckBox();
        pannaConna = new javax.swing.JCheckBox();
        clc = new javax.swing.JCheckBox();
        esBuah = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jumlah15 = new javax.swing.JTextField();
        jumlah14 = new javax.swing.JTextField();
        jumlah13 = new javax.swing.JTextField();
        jumlah12 = new javax.swing.JTextField();
        jumlah11 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        uangKembalian = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        uangMasuk = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        totalPesanan = new javax.swing.JTextArea();
        buttonPesan = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));

        jPanel2.setPreferredSize(new java.awt.Dimension(561, 1397));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FOOD MENU");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel1.setText("Makanan:");

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel2.setText("Nama pemesan:");

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel3.setText("Jumlah:");

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel4.setText("Harga:");

        seblak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seblak.setText("Seblak");

        basoBakar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        basoBakar.setText("Baso Bakar");

        kebabTurki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kebabTurki.setText("Kebab Turki");

        frenchFries.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frenchFries.setText("French Fries");

        burger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        burger.setText("Burger");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("10K");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("5K");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("15K");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("15K");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("10K");

        jLabel11.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel11.setText("Minuman:");

        cappucino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cappucino.setText("Cappucino");

        kopiTubruk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kopiTubruk.setText("Kopi Tubruk");

        boba.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boba.setText("Boba");

        jusMangga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jusMangga.setText("Jus Mangga");

        jusAlpukat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jusAlpukat.setText("Jus Alpukat");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("10K");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("15K");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("15K");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("5K");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("10K");

        jLabel17.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel17.setText("Harga:");

        jLabel18.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel18.setText("Jumlah:");

        yougert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yougert.setText("Yougert");

        mochi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mochi.setText("Mochi");

        pannaConna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pannaConna.setText("Panna Conna");

        clc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clc.setText("Choco Lava Cake");

        esBuah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        esBuah.setText("Es Buah");

        jLabel19.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel19.setText("Desert:");

        jLabel20.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel20.setText("Harga:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("10K");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("5K");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("15K");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("15K");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("10K");

        jLabel26.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel26.setText("Jumlah:");

        jLabel27.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel27.setText("Uang Masuk:");

        jLabel28.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel28.setText("Uang Kembalian:");

        jLabel29.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel29.setText("Total Pesanan:");

        totalPesanan.setColumns(20);
        totalPesanan.setRows(5);
        jScrollPane1.setViewportView(totalPesanan);

        buttonPesan.setBackground(new java.awt.Color(0, 153, 255));
        buttonPesan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        buttonPesan.setForeground(new java.awt.Color(255, 255, 255));
        buttonPesan.setText("Pesan");
        buttonPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesanActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(51, 102, 0));
        buttonBatal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Bayar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 102, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reset");

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Konfirmasi Semua Pesanan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaPemesan)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(seblak)
                            .addComponent(basoBakar)
                            .addComponent(kebabTurki)
                            .addComponent(frenchFries)
                            .addComponent(burger))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cappucino)
                            .addComponent(kopiTubruk)
                            .addComponent(boba)
                            .addComponent(jusMangga)
                            .addComponent(jusAlpukat)
                            .addComponent(jLabel19)
                            .addComponent(esBuah)
                            .addComponent(clc)
                            .addComponent(pannaConna)
                            .addComponent(mochi)
                            .addComponent(yougert))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jumlah11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah15, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(uangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonPesan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonBatal))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel9)
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seblak)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basoBakar)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kebabTurki)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frenchFries)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burger)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cappucino)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kopiTubruk)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boba)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jusMangga)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jusAlpukat)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esBuah)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clc)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pannaConna)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mochi)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yougert)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPesan)
                    .addComponent(buttonBatal))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(43, 43, 43)
                .addComponent(jButton5)
                .addGap(100, 100, 100))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesanActionPerformed
        // TODO add your handling code here:
        // Daftar Makanan
        // harga seblak 10000
        if(seblak.isSelected()){
            int Jumlah = Integer.parseInt(jumlah1.getText());
            Date day = new Date();
            if (day.getDay() == 4) {
                double total = (Jumlah * 10000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk makanan Seblak\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Seblak : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 10000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Seblak : " + Double.toString(total) + "\n";
            }
        }
        
        // harga baso bakar = 5000
        if (basoBakar.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah2.getText());
            Date day = new Date();
            if (day.getDay() == 4) {
                double total = (Jumlah * 5000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk makanan Baso Bakar\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Baso Bakar : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 5000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Baso Bakar : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga kebab turki = 15000
        if (kebabTurki.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah3.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 15000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk makanan Kebab Turki\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Kebab Turki : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 15000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Kebab Turki : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga french fries = 15000
        if (frenchFries.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah4.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 15000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk makanan French Fries\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " French Fries : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 15000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " French Fries : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga burger = 15000
        if (burger.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah5.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 10000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk makanan Burger\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Burger : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 10000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Burger : " + Double.toString(total) + "\n";
            } 
        }
        
        // Daftar Minuman
        // harga cappucino = 10000
        if (cappucino.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah6.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 10000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk minuman Cappucino\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Cappucino : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 10000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Cappucino : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga kopi tubruk = 5000
        if (kopiTubruk.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah7.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 5000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk minuman Kopi Tubruk\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Kopi Tubruk : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 5000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Kopi Tubruk : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga boba = 5000
        if (boba.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah8.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 5000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk minuman Boba\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Boba : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 5000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Boba : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga jus mangga = 15000
        if (jusMangga.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah9.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 15000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk minuman Jus Mangga\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Jus Mangga : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 15000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Jus Mangga : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga jus alpukat = 10000
        if (jusAlpukat.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah10.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 10000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk minuman Jus Alpukat\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Jus Alpukat : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 10000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Jus Alpukat : " + Double.toString(total) + "\n";
            } 
        }
        
        // Daftar Desert
        // harga es buah = 10000
        if (esBuah.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah11.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 10000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk desert Es Buah\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Es Buah : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 10000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Es Buah : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga choco lava cake = 5000
        if (clc.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah12.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 5000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk desert Choco Lava Cake\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Choco Lava Cake : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 5000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Choco Lava Cake : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga panna conna = 15000
        if (pannaConna.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah13.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 15000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk desert Panna Conna\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Panna Conna : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 15000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Panna Conna : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga panna conna = 15000
        if (mochi.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah14.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 15000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk desert Mochi\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Mochi : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 15000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Mochi : " + Double.toString(total) + "\n";
            } 
        }
        
        // harga yougert = 10000
        if (mochi.isSelected()) {
            int Jumlah = Integer.parseInt(jumlah14.getText());
            Date day = new Date();
            if (day.getDay() == 7) {
                double total = (Jumlah * 10000) * 0.7;
                diskon += "Anda dapat diskon 30% untuk desert Yougert\n";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Yougert : " + Double.toString(total) + "\n";
            } else {
                double total = Jumlah * 10000;
                diskon = "-";
                bayar = bayar + total;
                tampil += "Harga " + Integer.toString(Jumlah) + " Yougert : " + Double.toString(total) + "\n";
            } 
        }
        
        totalPesanan.setText("==================================\n" + namaPemesan.getText() + "\n==================================\n" + "Diskon Anda : \n" + diskon + "\n==================================\n" + tampil + "==================================\n" + "Total Pesanan : " + bayar);
        buttonPesan.setVisible(false);
    }//GEN-LAST:event_buttonPesanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int uMasuk = Integer.parseInt(uangMasuk.getText());
        double kembalian = uMasuk - bayar;
        if(kembalian <= 0) {
            JOptionPane.showMessageDialog(this, "Uangnya Kurang");
        } else {
            uangKembalian.setText(Double.toString(kembalian));  
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        buttonPesan.setVisible(true);
        tampil = "";
        diskon="";
        bayar=0;
        totalPesanan.setText(Double.toString(bayar));
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox basoBakar;
    private javax.swing.JCheckBox boba;
    private javax.swing.JCheckBox burger;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonPesan;
    private javax.swing.JCheckBox cappucino;
    private javax.swing.JCheckBox clc;
    private javax.swing.JCheckBox esBuah;
    private javax.swing.JCheckBox frenchFries;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah1;
    private javax.swing.JTextField jumlah10;
    private javax.swing.JTextField jumlah11;
    private javax.swing.JTextField jumlah12;
    private javax.swing.JTextField jumlah13;
    private javax.swing.JTextField jumlah14;
    private javax.swing.JTextField jumlah15;
    private javax.swing.JTextField jumlah2;
    private javax.swing.JTextField jumlah3;
    private javax.swing.JTextField jumlah4;
    private javax.swing.JTextField jumlah5;
    private javax.swing.JTextField jumlah6;
    private javax.swing.JTextField jumlah7;
    private javax.swing.JTextField jumlah8;
    private javax.swing.JTextField jumlah9;
    private javax.swing.JCheckBox jusAlpukat;
    private javax.swing.JCheckBox jusMangga;
    private javax.swing.JCheckBox kebabTurki;
    private javax.swing.JCheckBox kopiTubruk;
    private javax.swing.JCheckBox mochi;
    private javax.swing.JTextField namaPemesan;
    private javax.swing.JCheckBox pannaConna;
    private javax.swing.JCheckBox seblak;
    private javax.swing.JTextArea totalPesanan;
    private javax.swing.JTextField uangKembalian;
    private javax.swing.JTextField uangMasuk;
    private javax.swing.JCheckBox yougert;
    // End of variables declaration//GEN-END:variables
}
